//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavornCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesajKutusu
    {
        public int MesajId { get; set; }
        public string Isim { get; set; }
        public string MailAdres { get; set; }
        public string Telefon { get; set; }
        public string Mesaj { get; set; }
    }
}
