//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavornCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resimler
    {
        public int ResimId { get; set; }
        public string ResimAd { get; set; }
        public int UrunId { get; set; }
        public string ResimYol { get; set; }
    
        public virtual Urunler Urunler { get; set; }
    }
}
