//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavornCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int SepetId { get; set; }
        public Nullable<int> UrunId { get; set; }
        public string UrunAd { get; set; }
        public Nullable<decimal> UrunFiyat { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public Nullable<decimal> GenelToplam { get; set; }
        public Nullable<int> KargoFiyat { get; set; }
        public string KargoTur { get; set; }
        public Nullable<decimal> Toplam { get; set; }
        public Nullable<int> Adet { get; set; }
        public string MusteriMail { get; set; }
    
        public virtual Urunler Urunler { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
