//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavornCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparisler()
        {
            this.Uyeler = new HashSet<Uyeler>();
        }
    
        public int SiparisId { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public string EkleyenKullaniciAdi { get; set; }
        public int SiparisDurumId { get; set; }
        public string TeslimatKargoTuruAdi { get; set; }
        public decimal NetTutar { get; set; }
        public decimal KargoTutari { get; set; }
        public string TeslimAlacakKisiAdi { get; set; }
        public string TeslimAlacakKisiSoyadi { get; set; }
        public string TeslimatAdresi { get; set; }
        public string TeslimatPostaKodu { get; set; }
        public string TeslimatSehir { get; set; }
        public string Teslimatİlce { get; set; }
        public string TeslimatSemt { get; set; }
        public string MusteriMail { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public Nullable<System.DateTime> GonderilmeTarihi { get; set; }
        public string TransactionId { get; set; }
        public string TrackingId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uyeler> Uyeler { get; set; }
    }
}
