//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavornCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.Yorumlar1 = new HashSet<Yorumlar>();
        }
    
        public int Id { get; set; }
        public string UrunAd { get; set; }
        public string Aciklama { get; set; }
        public decimal UrunFiyat { get; set; }
        public int Stok { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public int KategoriId { get; set; }
        public int MarkaId { get; set; }
        public Nullable<int> YorumId { get; set; }
        public string ResimUrl { get; set; }
        public Nullable<int> ResimId { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Markalar Markalar { get; set; }
        public virtual Yorumlar Yorumlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlar1 { get; set; }
    }
}
