//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavornCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        public int Id { get; set; }
        public string UyeAd { get; set; }
        public string UyeSoyad { get; set; }
        public string Mail { get; set; }
        public Nullable<int> SiparisId { get; set; }
        public string TcKimlikNo { get; set; }
        public string Adres { get; set; }
        public string TeslimatAdresi { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Sifre { get; set; }
        public string Telefon { get; set; }
        public string Sehir { get; set; }
        public string Ulke { get; set; }
        public string Ilce { get; set; }
    }
}
